apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server:latest
          ports:
            - containerPort: 4000
            - containerPort: 4200
          env:
            - name: NODE_ENV
              value: "development"
            - name: DATABASE_HOST
              value: "postgresdb"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_NAME
              value: "postgres"
          volumeMounts:
            - name: server-volume
              mountPath: /server
            - name: server-node-modules
              mountPath: /server/node_modules
      volumes:
        - name: server-volume
          hostPath:
            path: ./server
        - name: server-node-modules
          emptyDir: {}
